#!/bin/bash
#Задание:
#На bash написать скрипт:
#1. Получить из таблицы test (SQLite test.db) все уникальные url c bt = 5.
#2. Проверить, сколько раз в файле (test.txt) встречался каждый полученный из бд url.\
#Если > 0 - вывести домен и сколько раз он встретился в файле. В выводе не должны повторяться домены, каждый домен с новой строки.
#Пример вывода:
#example.com 3
#example.org 4
sqlite3 test.db 'SELECT url, bt FROM test WHERE bt='5';' > testBD.txt
sed -i "s/.\{,3\}$//" testBD.txt
sort testBD.txt | uniq > testBD2.txt
rm testBD.txt
for name in $(cat testBD2.txt) ;
do
  for ses in $(grep $name test.txt | wc -l) 
  do
  echo "$name $ses" >> testBD.txt 
  done 
done
sed -i '/0/d' testBD.txt
# можно убрать ключь -i и тогда на экране сразу появиться результат.
rm testBD2.txt
cat testBD.txt
#итоговый результат выводится на экран с файла, 
#а так же записан в файл
