#!/bin/bash

iptables -L

iptables -A INPUT -p tcp --dport=22 -j ACCEPT
iptables -A INPUT -p tcp --dport=443 -j ACCEPT
iptables -A INPUT -p tcp --dport=80 -j ACCEPT
iptables -A INPUT -p tcp --dport=3306 -j ACCEPT
iptables -A INPUT -p tcp --dport=3000 -j ACCEPT
iptables -A INPUT -p tcp --dport=5601 -j ACCEPT
iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -p icmp -j ACCEPT
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -P INPUT DROP

cd /home/
iptables-save > ./iptables.rules

yum install iptables-services
systemctl start iptables
iptables-restore < ./iptables.rules
service iptables save

iptables -nvL --line-numbers


